config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "landing#index"

  resources :posts do
    resources :replies
  end

  constraints subdomain: /.*/ do
    resources :accounts, path: :profiles, as: :profiles, controller: :profiles
    resources :accounts

    resources :posts, path: :community, only: :index
    resources :posts, path: :following, only: :index

    resources :favorites, only: [:create, :show]
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  belongs_to :in_reply_to,
    class_name: 'Post', optional: true, dependent: :destroy
  has_many :replies,
           class_name: 'Post',
           foreign_key: 'in_reply_to_id',
           inverse_of: :in_reply_to,
           dependent: :destroy
  has_many :favorites
  has_many_attached :attachments

  # I need to choose how I want to handle references to user like the like
  # button before we can broadcast from the model so this is a future goal
  # after_create_commit do
  #   broadcast_prepend_to :posts, partial: "posts/post", locals: { post: self }
  # end

  scope :original_post, -> { where(in_reply_to: nil) }
  scope :community, ->(community) do
    if community.present?
      joins(account: :user)
        .where(users: { community: Community.find_by(name: community) })
    else
      Post.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include CommunitySubdomain
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.community(request.subdomain).original_post.includes(
      :favorites,
      attachments_attachments: [:blob],
      account: { avatar_attachment: :blob },
      replies: [:account]
    ).order(created_at: :desc).paginate(page: params[:page], per_page: 3)

    # We need this because rails favors text/vnd.turbo-stream.html which we use
    # for infinite scrolling, but breaks redirects
    respond_to do |format|
      if request.headers["Turbo-Frame"].present?
        format.turbo_stream
      else
        format.html
      end
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @replies = @post.replies
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.account = current_user.account
    @post.attachments.attach(params[:post][:attachments])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, notice: "Post was successfully deleted.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :in_reply_to_id, :attachments)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def community_path
    "/community"
  end
end

app/views/posts/_form.html.erb
<%= turbo_frame_tag "new_post", target: "_top" do %>
  <%= form_with(model: post,
                data: { controller: "form-reset",
                        action: "turbo:submit-end->form-reset#reset" }) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="block">
      <%= form.textarea :body, class: 'textarea card', placeholder: 'What\'s on your mind?' %>
    </div>
    <div class="block">
    </div>
    <div class="file block">
      <label class="file-label">
        <%= form.file_field :attachments, multiple: true, class: "file-input" %>
        <span class="file-cta">
          <span class="file-icon">📸</span>
          <span class="file-label"> Choose a file… </span>
        </span>
      </label>
    </div>


    <div>
      <%= form.submit class: "button is-info" %>
    </div>
  <% end %>
<% end %>

app/views/posts/_interactions.html.erb
<%= turbo_frame_tag dom_id(post, :interactions) do %>
  <div class="level-right">
    <p class="is-7">
    <%= link_to pluralize(post.favorites.length, "favorite"), "#", data: { turbo_frame: '_top' } %>
    &#183;
    <%= link_to pluralize(post.replies.length, "comment"), post_path(post), data: { turbo_frame: '_top' } %>
    </p>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="box is-primary" id="<%= dom_id post %>">
  <div class="media">
    <div class="media-left">
      <%= link_to profile_path(post.account), data: { turbo_frame: '_top' } do %>
        <figure class="image is-48x48">
          <% if post.account.avatar.present? %>
            <%= image_tag post.account.avatar, class: 'is-rounded' %>
          <% else %>
            <img class="is-rounded" src="https://bulma.io/assets/images/placeholders/96x96.png" alt="Placeholder image" />
          <% end %>
        </figure>
      <% end %>
    </div>
    <%= link_to profile_path(post.account), data: { turbo_frame: '_top' } do %>
      <div class="media-content">
        <p class="title is-5">
          <%= post.account.display_name %>
        </p>
        <p class="subtitle is-7">
          @<%= post.account.username %>
        </p>
      </div>
    <% end %>
  </div>
  <div class="content">
    <p><%= post.body %></p>
  </div>
  <div class="attachments block">
    <div class="grid">
      <% post.attachments.each do |attachment| %>
        <div class="cell">
          <% if attachment.representable? %>
            <% if attachment.video? %>
              <%= video_tag url_for(attachment), controls: true %>
            <% else %>
              <%= image_tag attachment.representation(resize_to_limit: [500, 500]), class: "image" %>
            <% end %>
          <% else %>
            <%= link_to rails_blob_path(attachment, disposition: "attachment") do %>
              <%= image_tag "placeholder.png", alt: "Download attachment" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <nav class="level">
    <div class="level-left">
      <% if user_signed_in? %>
        <div class="actions">
          <%= link_to "❤️ Like", favorites_path(account_id: current_user.account, post_id: post), class: 'button is-small is-rounded', data: { turbo_method: :post } %>
          <%= link_to "💬  Comment", post_path(post), class: 'button is-small is-rounded' %>
          <%= link_to "🌐  Share", "#", class: 'button is-small is-rounded' %>
        </div>
      <% end %>
    </div>
    <div class="level-right">
      <%= turbo_frame_tag dom_id(post, :interactions) do %>
        <div class="level-right">
          <p class="is-7">
          <%= link_to pluralize(post.favorites.length, "favorite"), "#", data: { turbo_frame: '_top' } %>
          &#183;
          <%= link_to pluralize(post.replies.length, "comment"), post_path(post), data: { turbo_frame: '_top' } %>
          </p>
        </div>
      <% end %>
    </div>
  </nav>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
  <%= render partial: "post", locals: { post: @post } %>
<% end %>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= turbo_frame_tag "posts", src: posts_path(format: :turbo_stream) %>

<% if @posts.next_page %>
  <%= turbo_frame_tag "load_more", src: posts_path(page: @posts.next_page, format: :turbo_stream), loading: :lazy %>
<% end %>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append "posts" do %>
  <%= render @posts %>
<% end %>

<% if @posts.next_page %>
  <%= turbo_stream.replace "load_more" do %>
    <%= turbo_frame_tag "load_more", src: posts_path(page: @posts.next_page, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "Back", root_path, class: 'button is-small block' %>

<%= render @post, user: current_user %>
<%= render "replies/reply_form", in_reply_to: @post, reply: Post.new %>

<div class="content">
  <%= turbo_frame_tag "replies", src: post_replies_path(@post) %>
</div>

<div>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>