config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "landing#index"

  resources :posts do
    resources :replies
  end

  constraints subdomain: /.*/ do
    resources :accounts, path: :profiles, as: :profiles, controller: :profiles
    resources :accounts

    resources :posts, path: :community, only: :index
    resources :posts, path: :following, only: :index

    resources :favorites, only: [:create, :show]
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-background-light">
  <head>
    <title><%= content_for(:title) || "Sapling" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Sapling">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container page-content">
      <div class="columns is-desktop">
        <div class="column pl-0 is-hidden-touch">
          <div class="navbar-brand">
            <b>
              <%= link_to "🌱 Sapling", root_path %>
            </b>
          </div>

          <div class="block">
            <% if user_signed_in? %>
              <div class="is-hidden-touch">
                <%= turbo_frame_tag "new_post", src: new_post_path, target: "_top", class: "block" %>
              </div>
            <% else %>
              <h1 class="subtitle">
                <strike>Social Media</strike>
                <b>Social Web</b>
              </h1>
              <p class=block>
                This is the social web home of Dev/Test, who have taken control
                of their online presence using <b><a>🌱 Sapling</a></b>
              </p>
              <p>
                <b><a>🌱 Sapling</a></b> is building for the social web, an antidote to big
                tech and corporate controlled social media. You can learn more
                about what that means <a>here</a>
              </p>
            <% end %>
          </div>
          <%= render "shared/flash" %>
        </div>

        <div class="column is-three-fifths-desktop">
          <%= yield %>
        </div>

        <div class="column pr-0 is-hidden-touch">
          <aside class="menu block">
            <p class="menu-label">Feeds</p>
            <ul class="menu-list">
              <li><%= link_to "Community", community_path, class: "has-background-light" %></li>
              <li><%= link_to "Global", posts_url(subdomain: nil), class: "has-background-light" %></li>
            </ul>
            <% if user_signed_in? %>
              <p class="menu-label">Management</p>
              <ul class="menu-list">
                <li><a class="has-background-light">Preferences</a></li>
              </ul>
            <% end %>
          </aside>

          <div class="buttons">
            <% unless user_signed_in? %>
              <%= link_to "Sign Up", new_user_registration_path, class: 'button is-info' %>
              <%= link_to "Log In", new_user_session_path, class: 'button is-light' %>
            <% else %>
              <%= button_to "Sign Out", destroy_user_session_path, { method: :delete } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="mobile-nav top is-hidden-desktop">
      <div class="level-left navbar-brand">
        <b>
          <%= link_to "🌱 Sapling", root_path %>
        </b>
      </div>
      <div class="level-left">
      </div>
    </div>
    <div class="mobile-nav bottom is-hidden-desktop">
      <div><%= link_to "🏠", community_path %></div>
      <div><%= link_to "🌎", posts_url(subdomain: nil) %></div>
      <div><%= link_to "➕", new_post_path %></div>
      <div><%= link_to "🔎", "#" %></div>
      <div><%= link_to "⚙️", "#" %></div>
    </div>
  </body>
</html>